name: Git Tag Annotation
description: Get the annotation associated with a git tag
author: Eric Cornelissen

inputs:
  tag:
    description: tag of interest (defaults to the GITHUB_REF environment variable)
    required: false

outputs:
  git-tag-annotation:
    description: The git tag annotation
    value: ${{ steps.tag.outputs.annotation }}

runs:
  using: composite
  steps:
    - name: Get tag annotation
      id: tag
      run: $GITHUB_ACTION_PATH/src/main.sh
      shell: bash
      env:
        GITHUB_REF: $GITHUB_REF
        GITHUB_OUTPUT: $GITHUB_OUTPUT
        PROVIDED_TAG: ${{ inputs.tag }}

branding:
  icon: tag
  color: gray-dark
