#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
STASH_COUNT_BEFORE=$(get_stash_count)
git stash push --include-untracked --keep-index --quiet

# Checks
npm run format
git update-index --again

# Post
STASH_COUNT_AFTER=$(get_stash_count)
if [ "$STASH_COUNT_BEFORE" -lt "$STASH_COUNT_AFTER" ]
then
  git stash pop --quiet
fi
