#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
if [ ! "$(IS_MERGING)" ]; then
  git stash push --include-untracked --quiet
fi

# Checks
npm run vet
npm run lint
npm run lint:md
npm run test

if command -v gitleaks > /dev/null; then
  gitleaks protect
fi

# Post
if [ "$(DID_STASH)" ]; then
  git stash pop --quiet
fi
