#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
if [ ! "$(IS_MERGING)" ]; then
  git stash push --include-untracked --quiet
fi

# Checks
npm run vet
npm run license-check
npm run lint
npm run lint:md
npm run test

if command -v actionlint > /dev/null; then
  npm run lint:ci
fi
if command -v docker > /dev/null; then
  npm run lint:docker
fi
if command -v shellcheck > /dev/null; then
  npm run lint:sh
fi
if command -v gitleaks > /dev/null; then
  gitleaks protect
fi

# Post
if [ "$(DID_STASH)" ]; then
  git stash pop --quiet
fi
