#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
LIB_STAGED_COUNT=$(git diff --name-only --staged lib/ | wc --lines)
if [ "$LIB_STAGED_COUNT" -ne "0" ]; then
  echo "[INFO] All changes to the lib/ directory have been unstaged"
  echo "[INFO] Changes in the lib/ directory should not be committed"
  git restore --staged lib/
fi

if [ ! "$(IS_MERGING)" ]; then
  git stash push --include-untracked --keep-index --quiet
fi

# Checks
npm run vet
npm run lint:md
npm run format
git update-index --again

if command -v gitleaks > /dev/null; then
  gitleaks protect
fi

# Post
if [ "$(DID_STASH)" ]; then
  git stash pop --quiet
fi
