#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Pre
STASH_COUNT_BEFORE=$(get_stash_count)
if [ ! -f "$MERGE_HEAD" ]; then
  git stash push --include-untracked --quiet
fi

# Checks
npm run vet
npm run lint
npm run test

# Post
STASH_COUNT_AFTER=$(get_stash_count)
if [ "$STASH_COUNT_BEFORE" -lt "$STASH_COUNT_AFTER" ]; then
  git stash pop --quiet
fi
