name: Update lib/index.js
on:
  push:
    branches: [main]

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: npm
    - name: Initialize repository
      run: npm ci
    - name: Build lib/index.js
      run: npm run build
    - name: Push updates
      uses: stefanzweifel/git-auto-commit-action@v4.6.0
      with:
        commit_message: "chore: update lib/index.js"
        commit_options: "--no-verify"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
