name: Update lib/index.js
on:
  push:
    branches: [main]

permissions: read-all

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
    - name: Install Node.js
      uses: actions/setup-node@v2.5.1
      with:
        cache: npm
        node-version-file: .nvmrc
    - name: Initialize repository
      run: npm ci
    - name: Build lib/index.js
      run: npm run build
    - name: Push updates
      uses: stefanzweifel/git-auto-commit-action@v4.6.0
      with:
        commit_message: "chore: update lib/index.js"
        commit_options: "--no-verify"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
